patterns:
  project-cards:
    title: "project cards"
    description: |
      This will be used as cards that you can click and view each individual project.
    fields:
      - name: heading
        type: string
      - name: text
        type: string
      - name: 'url'
        type: 'string'
        exammple: '/images/'
